# Run r cmd check
on:
  push:
    paths-ignore:
      - '.github/**'
      - 'docs/**'
      - '**.md'
      - '**.MD'
      - '.gitignore'
      - '.Rbuildignore'
      - 'JOSS/**'
  pull_request:
  workflow_dispatch:
  schedule:
    # This should run the default branch weekly on sunday
    - cron: '0 0 * * 0'
name: call-r-cmd-check

jobs:
  call-workflow:
    uses: nmfs-fish-tools/ghactions4r/.github/workflows/r-cmd-check.yml@main
